#app:
#  kafka:
#    topic: "demo-topic"
#server:
#  port: 9091
#
#spring:
#  kafka:
#    producer:
#      bootstrap-servers: "rtry.ru:9092"
#      client-id: "demo-producer"
#    admin:
#      auto-create: false