#app:
#  kafka:
#    topic: "demo-topic"
#server:
#  port: 9091
#
#spring:
#  kafka:
#    consumer:
#      group-id: "test-group"
#      bootstrap-servers: "rtry.ru:9092"
#      client-id: "demo-consumer"
#      auto-offset-reset: earliest
#    producer:
#      bootstrap-servers: "rtry.ru:9092"
#      client-id: "demo-producer"
#    admin:
#      auto-create: false