spring:
  sql:
    init:
      mode: always
  docker:
    compose:
      file: './testcontainers/compose.yaml'
      start:
        command: up
        log-level: debug
      stop:
        command: down
        timeout: 10s
      lifecycle-management: start_and_stop